#define RootProcess 0;
int length;
int length_per_process;
int myStart;
int myCount=0;
int globalCount;
MPI_Status status;
int tag=1;
int i;
int p;
FILE * fp;
char filename[]="num.txt";
int exit(int num);
